# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/shunya/Dropbox/workspace/Python/serial_logger/serialLogger.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(681, 584)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_serial = QtGui.QHBoxLayout()
        self.horizontalLayout_serial.setObjectName(_fromUtf8("horizontalLayout_serial"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.comboBox = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox)
        self.horizontalLayout_serial.addLayout(self.formLayout)
        self.pushButton_update = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_update.sizePolicy().hasHeightForWidth())
        self.pushButton_update.setSizePolicy(sizePolicy)
        self.pushButton_update.setObjectName(_fromUtf8("pushButton_update"))
        self.horizontalLayout_serial.addWidget(self.pushButton_update)
        self.comboBox_baud = QtGui.QComboBox(self.widget)
        self.comboBox_baud.setMinimumSize(QtCore.QSize(98, 0))
        self.comboBox_baud.setObjectName(_fromUtf8("comboBox_baud"))
        self.comboBox_baud.addItem(_fromUtf8(""))
        self.comboBox_baud.addItem(_fromUtf8(""))
        self.comboBox_baud.addItem(_fromUtf8(""))
        self.comboBox_baud.addItem(_fromUtf8(""))
        self.comboBox_baud.addItem(_fromUtf8(""))
        self.comboBox_baud.addItem(_fromUtf8(""))
        self.comboBox_baud.addItem(_fromUtf8(""))
        self.comboBox_baud.addItem(_fromUtf8(""))
        self.horizontalLayout_serial.addWidget(self.comboBox_baud)
        self.pushButton = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_serial.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_serial)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_mqtt_host = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_mqtt_host.sizePolicy().hasHeightForWidth())
        self.lineEdit_mqtt_host.setSizePolicy(sizePolicy)
        self.lineEdit_mqtt_host.setObjectName(_fromUtf8("lineEdit_mqtt_host"))
        self.horizontalLayout.addWidget(self.lineEdit_mqtt_host)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_mqtt_port = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_mqtt_port.sizePolicy().hasHeightForWidth())
        self.lineEdit_mqtt_port.setSizePolicy(sizePolicy)
        self.lineEdit_mqtt_port.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_mqtt_port.setObjectName(_fromUtf8("lineEdit_mqtt_port"))
        self.horizontalLayout.addWidget(self.lineEdit_mqtt_port)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_mqtt_topic = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_mqtt_topic.sizePolicy().hasHeightForWidth())
        self.lineEdit_mqtt_topic.setSizePolicy(sizePolicy)
        self.lineEdit_mqtt_topic.setObjectName(_fromUtf8("lineEdit_mqtt_topic"))
        self.horizontalLayout.addWidget(self.lineEdit_mqtt_topic)
        self.pushButton_mqtt_connect = QtGui.QPushButton(self.widget)
        self.pushButton_mqtt_connect.setObjectName(_fromUtf8("pushButton_mqtt_connect"))
        self.horizontalLayout.addWidget(self.pushButton_mqtt_connect)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_save_file = QtGui.QHBoxLayout()
        self.horizontalLayout_save_file.setObjectName(_fromUtf8("horizontalLayout_save_file"))
        self.checkBox_csv = QtGui.QCheckBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_csv.sizePolicy().hasHeightForWidth())
        self.checkBox_csv.setSizePolicy(sizePolicy)
        self.checkBox_csv.setChecked(True)
        self.checkBox_csv.setObjectName(_fromUtf8("checkBox_csv"))
        self.horizontalLayout_save_file.addWidget(self.checkBox_csv)
        self.lineEdit = QtGui.QLineEdit(self.widget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_save_file.addWidget(self.lineEdit)
        self.pushButtonUpdateFileName = QtGui.QPushButton(self.widget)
        self.pushButtonUpdateFileName.setObjectName(_fromUtf8("pushButtonUpdateFileName"))
        self.horizontalLayout_save_file.addWidget(self.pushButtonUpdateFileName)
        self.verticalLayout.addLayout(self.horizontalLayout_save_file)
        self.horizontalLayout_live_text = QtGui.QHBoxLayout()
        self.horizontalLayout_live_text.setObjectName(_fromUtf8("horizontalLayout_live_text"))
        self.checkBox_log = QtGui.QCheckBox(self.widget)
        self.checkBox_log.setChecked(True)
        self.checkBox_log.setObjectName(_fromUtf8("checkBox_log"))
        self.horizontalLayout_live_text.addWidget(self.checkBox_log)
        self.checkBox_autoscroll = QtGui.QCheckBox(self.widget)
        self.checkBox_autoscroll.setChecked(True)
        self.checkBox_autoscroll.setObjectName(_fromUtf8("checkBox_autoscroll"))
        self.horizontalLayout_live_text.addWidget(self.checkBox_autoscroll)
        self.verticalLayout.addLayout(self.horizontalLayout_live_text)
        self.textBrowser_log = QtGui.QTextBrowser(self.widget)
        self.textBrowser_log.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textBrowser_log.setObjectName(_fromUtf8("textBrowser_log"))
        self.verticalLayout.addWidget(self.textBrowser_log)
        self.plotwdg = PlotWidget(self.splitter)
        self.plotwdg.setObjectName(_fromUtf8("plotwdg"))
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_rightside = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_rightside.setObjectName(_fromUtf8("verticalLayout_rightside"))
        self.groupBox_format = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_format.setObjectName(_fromUtf8("groupBox_format"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_format)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.radioButton_csv = QtGui.QRadioButton(self.groupBox_format)
        self.radioButton_csv.setChecked(True)
        self.radioButton_csv.setObjectName(_fromUtf8("radioButton_csv"))
        self.horizontalLayout_8.addWidget(self.radioButton_csv)
        self.radioButton_json = QtGui.QRadioButton(self.groupBox_format)
        self.radioButton_json.setObjectName(_fromUtf8("radioButton_json"))
        self.horizontalLayout_8.addWidget(self.radioButton_json)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.verticalLayout_rightside.addWidget(self.groupBox_format)
        self.groupBox_plot_control = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_plot_control.setObjectName(_fromUtf8("groupBox_plot_control"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_plot_control)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_liveUpdate = QtGui.QGroupBox(self.groupBox_plot_control)
        self.groupBox_liveUpdate.setCheckable(True)
        self.groupBox_liveUpdate.setChecked(True)
        self.groupBox_liveUpdate.setObjectName(_fromUtf8("groupBox_liveUpdate"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_liveUpdate)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBox_d0 = QtGui.QCheckBox(self.groupBox_liveUpdate)
        self.checkBox_d0.setChecked(False)
        self.checkBox_d0.setObjectName(_fromUtf8("checkBox_d0"))
        self.horizontalLayout_3.addWidget(self.checkBox_d0)
        self.lineEdit_d0 = QtGui.QLineEdit(self.groupBox_liveUpdate)
        self.lineEdit_d0.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_d0.setObjectName(_fromUtf8("lineEdit_d0"))
        self.horizontalLayout_3.addWidget(self.lineEdit_d0)
        self.pushButton_d0 = QtGui.QPushButton(self.groupBox_liveUpdate)
        self.pushButton_d0.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_d0.setStyleSheet(_fromUtf8("background-color: rgb(228,26,28);"))
        self.pushButton_d0.setText(_fromUtf8(""))
        self.pushButton_d0.setObjectName(_fromUtf8("pushButton_d0"))
        self.horizontalLayout_3.addWidget(self.pushButton_d0)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.checkBox_d1 = QtGui.QCheckBox(self.groupBox_liveUpdate)
        self.checkBox_d1.setChecked(True)
        self.checkBox_d1.setObjectName(_fromUtf8("checkBox_d1"))
        self.horizontalLayout_4.addWidget(self.checkBox_d1)
        self.lineEdit_d1 = QtGui.QLineEdit(self.groupBox_liveUpdate)
        self.lineEdit_d1.setObjectName(_fromUtf8("lineEdit_d1"))
        self.horizontalLayout_4.addWidget(self.lineEdit_d1)
        self.pushButton_d1 = QtGui.QPushButton(self.groupBox_liveUpdate)
        self.pushButton_d1.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_d1.setStyleSheet(_fromUtf8("background-color: rgb(55,126,184);"))
        self.pushButton_d1.setText(_fromUtf8(""))
        self.pushButton_d1.setObjectName(_fromUtf8("pushButton_d1"))
        self.horizontalLayout_4.addWidget(self.pushButton_d1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.checkBox_d2 = QtGui.QCheckBox(self.groupBox_liveUpdate)
        self.checkBox_d2.setChecked(False)
        self.checkBox_d2.setObjectName(_fromUtf8("checkBox_d2"))
        self.horizontalLayout_5.addWidget(self.checkBox_d2)
        self.lineEdit_d2 = QtGui.QLineEdit(self.groupBox_liveUpdate)
        self.lineEdit_d2.setObjectName(_fromUtf8("lineEdit_d2"))
        self.horizontalLayout_5.addWidget(self.lineEdit_d2)
        self.pushButton_d2 = QtGui.QPushButton(self.groupBox_liveUpdate)
        self.pushButton_d2.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_d2.setStyleSheet(_fromUtf8("background-color: rgb(77,175,74);"))
        self.pushButton_d2.setText(_fromUtf8(""))
        self.pushButton_d2.setObjectName(_fromUtf8("pushButton_d2"))
        self.horizontalLayout_5.addWidget(self.pushButton_d2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.checkBox_d3 = QtGui.QCheckBox(self.groupBox_liveUpdate)
        self.checkBox_d3.setChecked(False)
        self.checkBox_d3.setObjectName(_fromUtf8("checkBox_d3"))
        self.horizontalLayout_11.addWidget(self.checkBox_d3)
        self.lineEdit_d3 = QtGui.QLineEdit(self.groupBox_liveUpdate)
        self.lineEdit_d3.setObjectName(_fromUtf8("lineEdit_d3"))
        self.horizontalLayout_11.addWidget(self.lineEdit_d3)
        self.pushButton_d3 = QtGui.QPushButton(self.groupBox_liveUpdate)
        self.pushButton_d3.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_d3.setStyleSheet(_fromUtf8("background-color: rgb(152,78,163);"))
        self.pushButton_d3.setText(_fromUtf8(""))
        self.pushButton_d3.setObjectName(_fromUtf8("pushButton_d3"))
        self.horizontalLayout_11.addWidget(self.pushButton_d3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.checkBox_d4 = QtGui.QCheckBox(self.groupBox_liveUpdate)
        self.checkBox_d4.setChecked(False)
        self.checkBox_d4.setObjectName(_fromUtf8("checkBox_d4"))
        self.horizontalLayout_9.addWidget(self.checkBox_d4)
        self.lineEdit_d4 = QtGui.QLineEdit(self.groupBox_liveUpdate)
        self.lineEdit_d4.setObjectName(_fromUtf8("lineEdit_d4"))
        self.horizontalLayout_9.addWidget(self.lineEdit_d4)
        self.pushButton_d4 = QtGui.QPushButton(self.groupBox_liveUpdate)
        self.pushButton_d4.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_d4.setStyleSheet(_fromUtf8("background-color: rgb(255,127,0);"))
        self.pushButton_d4.setText(_fromUtf8(""))
        self.pushButton_d4.setObjectName(_fromUtf8("pushButton_d4"))
        self.horizontalLayout_9.addWidget(self.pushButton_d4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.checkBox_d5 = QtGui.QCheckBox(self.groupBox_liveUpdate)
        self.checkBox_d5.setChecked(False)
        self.checkBox_d5.setObjectName(_fromUtf8("checkBox_d5"))
        self.horizontalLayout_6.addWidget(self.checkBox_d5)
        self.lineEdit_d5 = QtGui.QLineEdit(self.groupBox_liveUpdate)
        self.lineEdit_d5.setObjectName(_fromUtf8("lineEdit_d5"))
        self.horizontalLayout_6.addWidget(self.lineEdit_d5)
        self.pushButton_d5 = QtGui.QPushButton(self.groupBox_liveUpdate)
        self.pushButton_d5.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_d5.setStyleSheet(_fromUtf8("background-color: rgb(255,255,51);"))
        self.pushButton_d5.setText(_fromUtf8(""))
        self.pushButton_d5.setObjectName(_fromUtf8("pushButton_d5"))
        self.horizontalLayout_6.addWidget(self.pushButton_d5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.checkBox_d6 = QtGui.QCheckBox(self.groupBox_liveUpdate)
        self.checkBox_d6.setChecked(False)
        self.checkBox_d6.setObjectName(_fromUtf8("checkBox_d6"))
        self.horizontalLayout_12.addWidget(self.checkBox_d6)
        self.lineEdit_d6 = QtGui.QLineEdit(self.groupBox_liveUpdate)
        self.lineEdit_d6.setObjectName(_fromUtf8("lineEdit_d6"))
        self.horizontalLayout_12.addWidget(self.lineEdit_d6)
        self.pushButton_d6 = QtGui.QPushButton(self.groupBox_liveUpdate)
        self.pushButton_d6.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_d6.setStyleSheet(_fromUtf8("background-color: rgb(166,86,40);"))
        self.pushButton_d6.setText(_fromUtf8(""))
        self.pushButton_d6.setObjectName(_fromUtf8("pushButton_d6"))
        self.horizontalLayout_12.addWidget(self.pushButton_d6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.checkBox_d7 = QtGui.QCheckBox(self.groupBox_liveUpdate)
        self.checkBox_d7.setChecked(False)
        self.checkBox_d7.setObjectName(_fromUtf8("checkBox_d7"))
        self.horizontalLayout_13.addWidget(self.checkBox_d7)
        self.lineEdit_d7 = QtGui.QLineEdit(self.groupBox_liveUpdate)
        self.lineEdit_d7.setObjectName(_fromUtf8("lineEdit_d7"))
        self.horizontalLayout_13.addWidget(self.lineEdit_d7)
        self.pushButton_d7 = QtGui.QPushButton(self.groupBox_liveUpdate)
        self.pushButton_d7.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_d7.setStyleSheet(_fromUtf8("background-color: rgb(247,129,191);"))
        self.pushButton_d7.setText(_fromUtf8(""))
        self.pushButton_d7.setObjectName(_fromUtf8("pushButton_d7"))
        self.horizontalLayout_13.addWidget(self.pushButton_d7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.verticalLayout_3.addWidget(self.groupBox_liveUpdate)
        self.pushButton_AutoRange = QtGui.QPushButton(self.groupBox_plot_control)
        self.pushButton_AutoRange.setObjectName(_fromUtf8("pushButton_AutoRange"))
        self.verticalLayout_3.addWidget(self.pushButton_AutoRange)
        self.verticalLayout_rightside.addWidget(self.groupBox_plot_control)
        self.horizontalLayout_2.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 681, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox_baud.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Serial Port", None))
        self.pushButton_update.setText(_translate("MainWindow", "Update", None))
        self.comboBox_baud.setItemText(0, _translate("MainWindow", "4800", None))
        self.comboBox_baud.setItemText(1, _translate("MainWindow", "9600", None))
        self.comboBox_baud.setItemText(2, _translate("MainWindow", "19200", None))
        self.comboBox_baud.setItemText(3, _translate("MainWindow", "38400", None))
        self.comboBox_baud.setItemText(4, _translate("MainWindow", "57600", None))
        self.comboBox_baud.setItemText(5, _translate("MainWindow", "115200", None))
        self.comboBox_baud.setItemText(6, _translate("MainWindow", "230400", None))
        self.comboBox_baud.setItemText(7, _translate("MainWindow", "250000", None))
        self.pushButton.setText(_translate("MainWindow", "Open", None))
        self.label_2.setText(_translate("MainWindow", "MQTT host", None))
        self.lineEdit_mqtt_host.setText(_translate("MainWindow", "192.168.10.110", None))
        self.label_3.setText(_translate("MainWindow", "port", None))
        self.lineEdit_mqtt_port.setText(_translate("MainWindow", "1883", None))
        self.label_4.setText(_translate("MainWindow", "Topic", None))
        self.lineEdit_mqtt_topic.setText(_translate("MainWindow", "currentsensors/washingmachine", None))
        self.pushButton_mqtt_connect.setText(_translate("MainWindow", "Connect", None))
        self.checkBox_csv.setText(_translate("MainWindow", "Save to file: ", None))
        self.pushButtonUpdateFileName.setText(_translate("MainWindow", "Current Time", None))
        self.checkBox_log.setText(_translate("MainWindow", "Show live log stream", None))
        self.checkBox_autoscroll.setText(_translate("MainWindow", "Auto Scroll", None))
        self.groupBox_format.setTitle(_translate("MainWindow", "Incoming stream format", None))
        self.radioButton_csv.setText(_translate("MainWindow", "CSV", None))
        self.radioButton_json.setText(_translate("MainWindow", "JSON", None))
        self.groupBox_plot_control.setTitle(_translate("MainWindow", "Plot", None))
        self.groupBox_liveUpdate.setTitle(_translate("MainWindow", "Live update", None))
        self.checkBox_d0.setText(_translate("MainWindow", "0", None))
        self.lineEdit_d0.setText(_translate("MainWindow", "data0", None))
        self.checkBox_d1.setText(_translate("MainWindow", "1", None))
        self.lineEdit_d1.setText(_translate("MainWindow", "data1", None))
        self.checkBox_d2.setText(_translate("MainWindow", "2", None))
        self.lineEdit_d2.setText(_translate("MainWindow", "data2", None))
        self.checkBox_d3.setText(_translate("MainWindow", "3", None))
        self.lineEdit_d3.setText(_translate("MainWindow", "data3", None))
        self.checkBox_d4.setText(_translate("MainWindow", "4", None))
        self.lineEdit_d4.setText(_translate("MainWindow", "data4", None))
        self.checkBox_d5.setText(_translate("MainWindow", "5", None))
        self.lineEdit_d5.setText(_translate("MainWindow", "data5", None))
        self.checkBox_d6.setText(_translate("MainWindow", "6", None))
        self.lineEdit_d6.setText(_translate("MainWindow", "data6", None))
        self.checkBox_d7.setText(_translate("MainWindow", "7", None))
        self.lineEdit_d7.setText(_translate("MainWindow", "data7", None))
        self.pushButton_AutoRange.setText(_translate("MainWindow", "AutoRange", None))

from pyqtgraph import PlotWidget
