# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/shunya/Dropbox/workspace/Python/serial_logger/serialLogger.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(878, 630)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.comboBox = QtGui.QComboBox(self.layoutWidget)
        self.comboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox)
        self.horizontalLayout.addLayout(self.formLayout)
        self.comboBox_6 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox_6)
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_update = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_update.setObjectName(_fromUtf8("pushButton_update"))
        self.horizontalLayout.addWidget(self.pushButton_update)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.checkBox = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButtonUpdateFileName = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonUpdateFileName.setObjectName(_fromUtf8("pushButtonUpdateFileName"))
        self.horizontalLayout_2.addWidget(self.pushButtonUpdateFileName)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.textBrowser = QtGui.QTextBrowser(self.layoutWidget)
        self.textBrowser.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.verticalLayout_5.addWidget(self.textBrowser)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_4 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.radioButton_csv = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_csv.setChecked(True)
        self.radioButton_csv.setObjectName(_fromUtf8("radioButton_csv"))
        self.horizontalLayout_8.addWidget(self.radioButton_csv)
        self.radioButton_json = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_json.setObjectName(_fromUtf8("radioButton_json"))
        self.horizontalLayout_8.addWidget(self.radioButton_json)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.spinBox_ncolumns = QtGui.QSpinBox(self.groupBox_4)
        self.spinBox_ncolumns.setMinimum(1)
        self.spinBox_ncolumns.setProperty("value", 4)
        self.spinBox_ncolumns.setObjectName(_fromUtf8("spinBox_ncolumns"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBox_ncolumns)
        self.horizontalLayout_9.addLayout(self.formLayout_2)
        self.pushButton_updateDataObjects = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_updateDataObjects.setObjectName(_fromUtf8("pushButton_updateDataObjects"))
        self.horizontalLayout_9.addWidget(self.pushButton_updateDataObjects)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_liveUpdate = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_liveUpdate.setCheckable(True)
        self.groupBox_liveUpdate.setChecked(True)
        self.groupBox_liveUpdate.setObjectName(_fromUtf8("groupBox_liveUpdate"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_liveUpdate)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBox_d0 = QtGui.QCheckBox(self.groupBox_liveUpdate)
        self.checkBox_d0.setChecked(True)
        self.checkBox_d0.setObjectName(_fromUtf8("checkBox_d0"))
        self.horizontalLayout_3.addWidget(self.checkBox_d0)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_liveUpdate)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_liveUpdate)
        self.pushButton_2.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);"))
        self.pushButton_2.setText(_fromUtf8(""))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.checkBox_marker0 = QtGui.QCheckBox(self.groupBox_liveUpdate)
        self.checkBox_marker0.setObjectName(_fromUtf8("checkBox_marker0"))
        self.horizontalLayout_3.addWidget(self.checkBox_marker0)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.checkBox_d1 = QtGui.QCheckBox(self.groupBox_liveUpdate)
        self.checkBox_d1.setChecked(True)
        self.checkBox_d1.setObjectName(_fromUtf8("checkBox_d1"))
        self.horizontalLayout_4.addWidget(self.checkBox_d1)
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_liveUpdate)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_liveUpdate)
        self.pushButton_3.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_3.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 0);"))
        self.pushButton_3.setText(_fromUtf8(""))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.checkBox_marker0_2 = QtGui.QCheckBox(self.groupBox_liveUpdate)
        self.checkBox_marker0_2.setObjectName(_fromUtf8("checkBox_marker0_2"))
        self.horizontalLayout_4.addWidget(self.checkBox_marker0_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.checkBox_d3 = QtGui.QCheckBox(self.groupBox_liveUpdate)
        self.checkBox_d3.setChecked(True)
        self.checkBox_d3.setObjectName(_fromUtf8("checkBox_d3"))
        self.horizontalLayout_5.addWidget(self.checkBox_d3)
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_liveUpdate)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_5.addWidget(self.lineEdit_4)
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_liveUpdate)
        self.pushButton_4.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_4.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 255);"))
        self.pushButton_4.setText(_fromUtf8(""))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.checkBox_marker0_3 = QtGui.QCheckBox(self.groupBox_liveUpdate)
        self.checkBox_marker0_3.setObjectName(_fromUtf8("checkBox_marker0_3"))
        self.horizontalLayout_5.addWidget(self.checkBox_marker0_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.checkBox_d2 = QtGui.QCheckBox(self.groupBox_liveUpdate)
        self.checkBox_d2.setChecked(True)
        self.checkBox_d2.setObjectName(_fromUtf8("checkBox_d2"))
        self.horizontalLayout_6.addWidget(self.checkBox_d2)
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_liveUpdate)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_6.addWidget(self.lineEdit_5)
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_liveUpdate)
        self.pushButton_5.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_5.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 255);"))
        self.pushButton_5.setText(_fromUtf8(""))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.checkBox_marker0_4 = QtGui.QCheckBox(self.groupBox_liveUpdate)
        self.checkBox_marker0_4.setObjectName(_fromUtf8("checkBox_marker0_4"))
        self.horizontalLayout_6.addWidget(self.checkBox_marker0_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addWidget(self.groupBox_liveUpdate)
        self.pushButton_AutoRange = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_AutoRange.setObjectName(_fromUtf8("pushButton_AutoRange"))
        self.verticalLayout_3.addWidget(self.pushButton_AutoRange)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.plotwdg = PlotWidget(self.splitter_2)
        self.plotwdg.setObjectName(_fromUtf8("plotwdg"))
        self.horizontalLayout_7.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Port", None))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "4800", None))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "9600", None))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "19200", None))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "38400", None))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "57600", None))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "115200", None))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "230400", None))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "250000", None))
        self.pushButton.setText(_translate("MainWindow", "Open", None))
        self.pushButton_update.setText(_translate("MainWindow", "Update", None))
        self.checkBox.setText(_translate("MainWindow", "Save to ", None))
        self.pushButtonUpdateFileName.setText(_translate("MainWindow", "Current Time", None))
        self.label_2.setText(_translate("MainWindow", "Log", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Format", None))
        self.radioButton_csv.setText(_translate("MainWindow", "CSV", None))
        self.radioButton_json.setText(_translate("MainWindow", "JSON", None))
        self.label_3.setText(_translate("MainWindow", "Columns", None))
        self.pushButton_updateDataObjects.setText(_translate("MainWindow", "Update", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Plot", None))
        self.groupBox_liveUpdate.setTitle(_translate("MainWindow", "Live update", None))
        self.checkBox_d0.setText(_translate("MainWindow", "0", None))
        self.lineEdit_2.setText(_translate("MainWindow", "data0", None))
        self.checkBox_marker0.setText(_translate("MainWindow", "marker", None))
        self.checkBox_d1.setText(_translate("MainWindow", "1", None))
        self.lineEdit_3.setText(_translate("MainWindow", "data1", None))
        self.checkBox_marker0_2.setText(_translate("MainWindow", "marker", None))
        self.checkBox_d3.setText(_translate("MainWindow", "2", None))
        self.lineEdit_4.setText(_translate("MainWindow", "data2", None))
        self.checkBox_marker0_3.setText(_translate("MainWindow", "marker", None))
        self.checkBox_d2.setText(_translate("MainWindow", "3", None))
        self.lineEdit_5.setText(_translate("MainWindow", "data3", None))
        self.checkBox_marker0_4.setText(_translate("MainWindow", "marker", None))
        self.pushButton_AutoRange.setText(_translate("MainWindow", "AutoRange", None))

from pyqtgraph import PlotWidget
